In [1]:
import numpy as np

In [2]:
arrayA = [[1, -2, 3, 5], [2, 2, -1, 0], [3, 0, 1, 2], [1, 0, 2, 0]]

In [3]:
A = np.asarray(arrayA)

In [5]:
print(2*A)

[[ 2 -4  6 10]
 [ 4  4 -2  0]
 [ 6  0  2  4]
 [ 2  0  4  0]]


Matrix Transpose

In [6]:
print(A.T)

[[ 1  2  3  1]
 [-2  2  0  0]
 [ 3 -1  1  2]
 [ 5  0  2  0]]


Inverse Matrix 

In [7]:
print(np.linalg.inv(A))

[[-0.23529412 -0.23529412  0.58823529 -0.05882353]
 [ 0.29411765  0.79411765 -0.73529412  0.32352941]
 [ 0.11764706  0.11764706 -0.29411765  0.52941176]
 [ 0.29411765  0.29411765 -0.23529412 -0.17647059]]


Matrix Rank

In [8]:
print(np.linalg.matrix_rank(A))

4


Matrix Determinant

In [9]:
print(np.linalg.det(A))

34.00000000000001


Matrix EigenVector

In [13]:
np.linalg.eig(A)

(array([ 5.52552524+0.j        , -1.52204833+1.31733645j,
        -1.52204833-1.31733645j,  1.51857142+0.j        ]),
 array([[-0.68465996+0.j        ,  0.619935  +0.j        ,
          0.619935  -0.j        ,  0.11199539+0.j        ],
        [-0.21666012+0.j        , -0.34875983-0.24694874j,
         -0.34875983+0.24694874j, -0.93998928+0.j        ],
        [-0.60547918+0.j        , -0.31379356-0.41033136j,
         -0.31379356+0.41033136j, -0.22854692+0.j        ],
        [-0.34306572+0.j        , -0.263929  +0.31075191j,
         -0.263929  -0.31075191j, -0.22725204+0.j        ]]))

In [14]:
np.linalg.svd(A)

(array([[-0.8819521 ,  0.25706354, -0.24178316, -0.31244156],
        [ 0.05743106, -0.76320224, -0.26028922, -0.58862003],
        [-0.42722253, -0.58124436,  0.04756433,  0.69092224],
        [-0.19063859, -0.11660051,  0.93355667, -0.28023773]]),
 array([6.97059301, 3.8068416 , 1.85521105, 0.69063894]),
 array([[-0.32126336,  0.26952747, -0.50380033, -0.75520197],
        [-0.8221184 , -0.53601693,  0.18911937,  0.03226532],
        [ 0.16919264, -0.01995035,  0.78137601, -0.60035603],
        [ 0.43850318, -0.7997767 , -0.31602313, -0.2611543 ]]))