In [1]:
import torch

In [2]:
class Sigmoid(torch.nn.Module):
   def __init__(self):
       super(Sigmoid, self).__init__()
       self.U_1 = torch.tensor([[-0.3, 1.0, 1.2], [1.6, -1.0, -1.1]])
       self.U_2 = torch.tensor([[1.0, 1.0, -1.0], [0.7, 0.5, 1.0]])
       self.U_3 = torch.tensor([[0.5, -0.8, 1.0], [-0.1, 0.3, 0.4]])
       self.U_4 = torch.tensor([[1.0, 0.1, -0.2], [-0.2, 1.3, -0.4]])

   def forward(self, x):
       sigmoid = torch.nn.Sigmoid()
       h1 = torch.mm(x, self.U_1.t())
       a1 = sigmoid(h1)
       a1 = torch.tensor([[1, a1[0][0], a1[0][1]]])
       h2 = torch.mm(a1, self.U_2.t())
       a2 = sigmoid(h2)
       a2 = torch.tensor([[1, a2[0][0], a2[0][1]]])
       h3 = torch.mm(a2, self.U_3.t())
       a3 = sigmoid(h3)
       a3 = torch.tensor([[1, a3[0][0], a3[0][1]]])
       h4 = torch.mm(a3, self.U_4.t())
       a4 = sigmoid(h4)
       return a4

In [3]:
output = Sigmoid().forward(torch.tensor([[1.0, 1.0, 0.0]]))
print(output)

tensor([[0.7202, 0.6081]])


In [4]:
class LogisticSigmoid(torch.nn.Module):
   def __init__(self):
       super(LogisticSigmoid, self).__init__()
       self.U_1 = torch.tensor([[-0.3, 1.0, 1.2], [1.6, -1.0, -1.1]])
       self.U_2 = torch.tensor([[1.0, 1.0, -1.0], [0.7, 0.5, 1.0]])
       self.U_3 = torch.tensor([[0.5, -0.8, 1.0], [-0.1, 0.3, 0.4]])
       self.U_4 = torch.tensor([[1.0, 0.1, -0.2], [-0.2, 1.3, -0.4]])

   def forward(self, x):
       log_sigmoid = torch.nn.LogSigmoid()
       h1 = torch.mm(x, self.U_1.t())
       a1 = log_sigmoid(h1)
       a1 = torch.tensor([[1, a1[0][0], a1[0][1]]])
       h2 = torch.mm(a1, self.U_2.t())
       a2 = log_sigmoid(h2)
       a2 = torch.tensor([[1, a2[0][0], a2[0][1]]])
       h3 = torch.mm(a2, self.U_3.t())
       a3 = log_sigmoid(h3)
       a3 = torch.tensor([[1, a3[0][0], a3[0][1]]])
       h4 = torch.mm(a3, self.U_4.t())
       a4 = log_sigmoid(h4)
       return a4

In [5]:
output = LogisticSigmoid().forward(torch.tensor([[1.0, 1.0, 0.0]]))
print(output)

tensor([[-0.2814, -1.0840]])


In [6]:
true = torch.tensor([[0.0, 1.0]])

In [7]:
loss = torch.nn.functional.mse_loss(output, true)
print(loss)

tensor(2.2111)


In [8]:
class LogisticSigmoid(torch.nn.Module):
   def __init__(self):
       super(LogisticSigmoid, self).__init__()
       self.U_1 = torch.tensor([[-0.3, 1.0, 1.2], [1.6, -1.0, -1.1]])
       self.U_2 = torch.tensor([[1.0, 1.0, -1.0], [0.7, 0.5, 1.0]])
       self.U_3 = torch.tensor([[0.5, -0.8, 0.9], [-0.1, 0.3, 0.4]])
       self.U_4 = torch.tensor([[1.0, 0.1, -0.2], [-0.2, 1.3, -0.4]])

   def forward(self, x):
       log_sigmoid = torch.nn.LogSigmoid()
       h1 = torch.mm(x, self.U_1.t())
       a1 = log_sigmoid(h1)
       a1 = torch.tensor([[1, a1[0][0], a1[0][1]]])
       h2 = torch.mm(a1, self.U_2.t())
       a2 = log_sigmoid(h2)
       a2 = torch.tensor([[1, a2[0][0], a2[0][1]]])
       h3 = torch.mm(a2, self.U_3.t())
       a3 = log_sigmoid(h3)
       a3 = torch.tensor([[1, a3[0][0], a3[0][1]]])
       h4 = torch.mm(a3, self.U_4.t())
       a4 = log_sigmoid(h4)
       return a4

In [9]:
output = LogisticSigmoid().forward(torch.tensor([[1.0, 1.0, 0.0]]))
print(output)

tensor([[-0.2806, -1.0573]])


In [10]:
loss = torch.nn.functional.mse_loss(output, true)
print(loss)

tensor(2.1555)


In [11]:
class ReLU(torch.nn.Module):
   def __init__(self):
       super(ReLU, self).__init__()
       self.U_1 = torch.tensor([[-0.3, 1.0, 1.2], [1.6, -1.0, -1.1]])
       self.U_2 = torch.tensor([[1.0, 1.0, -1.0], [0.7, 0.5, 1.0]])
       self.U_3 = torch.tensor([[0.5, -0.8, 1.0], [-0.1, 0.3, 0.4]])
       self.U_4 = torch.tensor([[1.0, 0.1, -0.2], [-0.2, 1.3, -0.4]])

   def forward(self, x):
       relu = torch.nn.ReLU()
       h1 = torch.mm(x, self.U_1.t())
       a1 = relu(h1)
       a1 = torch.tensor([[1, a1[0][0], a1[0][1]]])
       h2 = torch.mm(a1, self.U_2.t())
       a2 = relu(h2)
       a2 = torch.tensor([[1, a2[0][0], a2[0][1]]])
       h3 = torch.mm(a2, self.U_3.t())
       a3 = relu(h3)
       a3 = torch.tensor([[1, a3[0][0], a3[0][1]]])
       h4 = torch.mm(a3, self.U_4.t())
       a4 = relu(h4)
       return a4

In [12]:
output = ReLU().forward(torch.tensor([[1.0, 1.0, 0.0]]))
print(output)

tensor([[0.9490, 1.0950]])
